apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: sno-cluster-1
  namespace: open-cluster-management
spec:
  clusterRef:
    name: sno-cluster-1
    namespace: open-cluster-management
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTDngV/AdTc1ALlWjqUi6SjZ2iu1E/2vZezNSiVCAFeQCgop2hp8/U6vz/qC4a4E4WWqgURsDrhaHxic7YCvQ7V6R/ukMV4qRPC326Gn4Thur7bkYb8axctUuuUM3AkZDg/KZ7NkZOV6/2I/WuTvQWc6sMj4AzwdcPmUfnIw6ziiHC8xpuNvggofAn9EqFc0POrLXZRBDF83Me9J9IwW0X9563IoxE9IixcmRudVXat99A0zUyGk6MriBmv/8WiVBbKaPXpgDmp40eek51PBm20/AByJuJ9gsV46wtm6tlqySzyY5pfEWXCAnDQeSquXzPR6cEdKMrK7y68qxfwLtmjpEJiNCZaCex4D4nHyS4BxHsfpYarGsqUqlAUGEMYrNqrcwzxtRGiiHB6TnCw12JGg6QSaazgpBp/GycEtlrxM4UasAdtH5nJSzgElPJSJTB7zgML7Dwb/SujCmrrT0NWczPjdTZzrF++oo4N13NDQIjng2PyLDR1H9GqJ0oeCPfiKMn7BCBoHxQoo8TQYAp7bd8ayj0jF34ZtIXrkw1yhfS6m9yNaplnV/CeniCJYUmuAov4DiqYfz1JKYh9jZlhjsSABcUw4ocsg0uAw5R53NokEKRB6YQJHLBjuSkfMFbBAVFwxCiXrGr9ECUqAmgdCll5G7k4MJUEskTCkt4xQ== vijjay12@oc3078654033.ibm.com"
  agentLabelSelector:
    matchLabels:
      cluster-name: sno-cluster-
  pullSecretRef:
    name: assisted-deployment-pull-secret
  ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/someconfig", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
  #  nmStateConfigLabelSelector:
  #  matchLabels:
  #    cluster-name: nmstate-vran-spoke-1
