apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: sno-cluster-1
  namespace: open-cluster-management
spec:
  clusterDeploymentRef:
    name: sno-cluster-1
  imageSetRef:
    name: img4.8.14-x86-64-appsub
  networking:
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    serviceNetwork:
      - "172.30.0.0/16"
    machineNetwork:
      - cidr: "9.37.195.0/26"
  provisionRequirements:
    controlPlaneAgents: 1
    workerAgents: 0
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTDngV/AdTc1ALlWjqUi6SjZ2iu1E/2vZezNSiVCAFeQCgop2hp8/U6vz/qC4a4E4WWqgURsDrhaHxic7YCvQ7V6R/ukMV4qRPC326Gn4Thur7bkYb8axctUuuUM3AkZDg/KZ7NkZOV6/2I/WuTvQWc6sMj4AzwdcPmUfnIw6ziiHC8xpuNvggofAn9EqFc0POrLXZRBDF83Me9J9IwW0X9563IoxE9IixcmRudVXat99A0zUyGk6MriBmv/8WiVBbKaPXpgDmp40eek51PBm20/AByJuJ9gsV46wtm6tlqySzyY5pfEWXCAnDQeSquXzPR6cEdKMrK7y68qxfwLtmjpEJiNCZaCex4D4nHyS4BxHsfpYarGsqUqlAUGEMYrNqrcwzxtRGiiHB6TnCw12JGg6QSaazgpBp/GycEtlrxM4UasAdtH5nJSzgElPJSJTB7zgML7Dwb/SujCmrrT0NWczPjdTZzrF++oo4N13NDQIjng2PyLDR1H9GqJ0oeCPfiKMn7BCBoHxQoo8TQYAp7bd8ayj0jF34ZtIXrkw1yhfS6m9yNaplnV/CeniCJYUmuAov4DiqYfz1JKYh9jZlhjsSABcUw4ocsg0uAw5R53NokEKRB6YQJHLBjuSkfMFbBAVFwxCiXrGr9ECUqAmgdCll5G7k4MJUEskTCkt4xQ== vijjay12@oc3078654033.ibm.com"
