apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-openshift-gitops.yaml
  - gitops-cluster-rolebinding.yaml
#  - app-project.yaml
  - argocd-ns.yaml  

    #  - clusters-app.yaml
  - site-config-crd.yaml
  - hook-cluster-sub-role.yaml      # sitecoonfigs.ran.openshift.io
  - hook-cluster-sub-binding.yaml   # sitecoonfigs.ran.openshift.io

    #  - policies-app.yaml
  - policy-gen-template-crd.yaml
  - hook-policies-sub-role.yaml        # policygentemplates.ran.openshift.io
  - hook-policies-sub-binding.yaml     # policygentemplates.ran.openshift.io
  - hook-policies-sub-acm-binding.yaml