---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
#    argocd.argoproj.io/sync-wave: "30"
  name: nodes-label-job-sno-5
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/node
              echo ""
              echo -n "Add node labels"
              until oc wait --selector=feature.node.kubernetes.io/network-sriov.capable=true,kubernetes.io/hostname=r13dell6 --for=condition=ready nodes
              do
                echo -n "...still waiting for applying labels"
                oc label node r13dell6 feature.node.kubernetes.io/network-sriov.capable=true
                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: nodes-label-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30