---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: combined-ran
  namespace: sno-5
spec:
  # The argocd project the application belongs to
  project: default
  destination:
    server: 'https://api.sno-5.vran.ibm.com:6443'
  source:
    repoURL: 'https://github.com/traghave123/samsung-gitops.git'
    targetRevision: master
    path: clusters/cluster-1.vran.ibm.com
    directory:
      recurse: false
  # Sync policy
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true 
      allowEmpty: true
    syncOptions:
      # (equivalent to 'kubectl apply --validate=true')
      - Validate=false
      - CreateNamespace=true
    retry:
      # unlimited if less than 0
      limit: -1
      backoff:
        # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        duration: 5s
        # a factor to multiply the base duration after each failed retry
        factor: 2
        # the maximum amount of time allowed for the backoff strategy
        maxDuration: 3m
