---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: node-configs
 namespace: sno-5
spec:
  syncPolicy: {}
  generators:
    - git:
        repoURL: 'https://github.com/traghave123/samsung-gitops.git'
        revision: HEAD
        files:
        - path: "clusters/cluster-1.vran.ibm.com/sites/*/worker-cu1/configs-*/config.json"
  template:
    metadata:
      name: '{{application-name}}'
      namespace: sno-5
    spec:
      project: default
      source:
        repoURL: 'https://github.com/traghave123/samsung-gitops.git'
        targetRevision: master
        path: '{{path}}'
      destination:
        server: '{{cluster-address}}'
      syncPolicy:
        automated:
          prune: false
          allowEmpty: true  
          selfHeal: true 
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: -1
        syncOptions:
        - Validate=false
        - CreateNamespace=true