---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: node-configs
 namespace: sno-5
spec:
  generators:
    - git:
        repoURL: 'https://github.com/traghave123/samsung-gitops.git'
        revision: HEAD
        files:
        - path: "clusters/cluster-1.vran.ibm.com/sites/*/*/configs-*/config.json"
  template:
    metadata:
      name: '{{application-name}}'
      namespace: sno-5
    spec:
      project: default
      source:
        repoURL: 'https://github.com/traghave123/samsung-gitops.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{cluster-address}}'