apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-1.vran.ibm.com-cnf-deploy
  namespace: cluster-1.vran.ibm.com
spec:
  destination:
    server: https://api.cluster-1.vran.ibm.com:6443
    namespace: openshift-gitops
  project: default
  source:
    directory:
      recurse: true
    path: clusters/cluster-1.vran.ibm.com/gitops-apps/remote-argocd
    repoURL: https://github.ibm.com/ocp48automation/telco-gitops.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true