---
apiVersion: sriovfec.intel.com/v2
kind: SriovFecClusterConfig
metadata:
  name: config
  namespace: vran-acceleration-operators
spec:
  nodes:
    - nodeName: aries11
      physicalFunctions:
        - pciAddress: 0000:c3:00.0
          pfDriver: pci-pf-stub
          vfDriver: vfio-pci
          vfAmount: 5
          bbDevConfig:
            acc100:
              # Programming mode: 0 = VF Programming, 1 = PF Programming
              pfMode: false
              numVfBundles: 5
              maxQueueSize: 1024
              uplink4G:
                numQueueGroups: 4
                numAqsPerGroups: 16
                aqDepthLog2: 5
              downlink4G:
                numQueueGroups: 4
                numAqsPerGroups: 16
                aqDepthLog2: 5
              uplink5G:
                numQueueGroups: 0
                numAqsPerGroups: 16
                aqDepthLog2: 4
              downlink5G:
                numQueueGroups: 0
                numAqsPerGroups: 16
                aqDepthLog2: 4
    - nodeName: aries14
      physicalFunctions:
        - pciAddress: 0000:c3:00.0
          pfDriver: pci-pf-stub
          vfDriver: vfio-pci
          vfAmount: 4
          bbDevConfig:
            acc100:
              # Programming mode: 0 = VF Programming, 1 = PF Programming
              pfMode: false
              numVfBundles: 4
              maxQueueSize: 1024
              uplink4G:
                numQueueGroups: 4
                numAqsPerGroups: 16
                aqDepthLog2: 5
              downlink4G:
                numQueueGroups: 4
                numAqsPerGroups: 16
                aqDepthLog2: 5
              uplink5G:
                numQueueGroups: 0
                numAqsPerGroups: 16
                aqDepthLog2: 4
              downlink5G:
                numQueueGroups: 0
                numAqsPerGroups: 16
                aqDepthLog2: 4
    - nodeName: aries19
      physicalFunctions:
        - pciAddress: 0000:c3:00.0
          pfDriver: pci-pf-stub
          vfDriver: vfio-pci
          vfAmount: 4
          bbDevConfig:
            acc100:
              # Programming mode: 0 = VF Programming, 1 = PF Programming
              pfMode: false
              numVfBundles: 4
              maxQueueSize: 1024
              uplink4G:
                numQueueGroups: 4
                numAqsPerGroups: 16
                aqDepthLog2: 5
              downlink4G:
                numQueueGroups: 4
                numAqsPerGroups: 16
                aqDepthLog2: 5
              uplink5G:
                numQueueGroups: 0
                numAqsPerGroups: 16
                aqDepthLog2: 4
              downlink5G:
                numQueueGroups: 0
                numAqsPerGroups: 16
                aqDepthLog2: 4

