---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: localstorage
  namespace: openshift-local-storage
spec:
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - r13dell6
  storageClassDevices:
    - storageClassName: localstorage
      volumeMode: Filesystem
      fsType: xfs 
      devicePaths: 
        - /dev/testvg/lv_data1
        - /dev/testvg/lv_data2
        - /dev/testvg/lv_data3
        - /dev/testvg/lv_data4
        - /dev/testvg/lv_data5
        - /dev/testvg/lv_data6
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    local.storage.openshift.io/owner-name: localstorage
    local.storage.openshift.io/owner-namespace: openshift-local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    