---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: ldc6-local-storage-server-profile-cu-dell-r740-00
  namespace: openshift-local-storage
spec:
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ran.openshift.io/ldc6-local-storage-server-profile-cu-dell-r740-00
            operator: Exists
  storageClassDevices:
    - storageClassName: localstorage
      volumeMode: Filesystem
      fsType: xfs 
      devicePaths: 
        - /dev/autopart/lv_1
        - /dev/autopart/lv_2
        - /dev/autopart/lv_3
        - /dev/autopart/lv_4
        - /dev/autopart/lv_5
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"