---
# To create the correct file use the following command:
#  oc create secret generic assisted-deployment-pull-secret -n assisted-installer \
#  --from-file=.dockerconfigjson=pull-secret.json --type=kubernetes.io/dockerconfigjson
apiVersion: v1
data:
  # assisted-deployment-pull-secret
  .dockerconfigjson: 'EXAMPLE'
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: assisted-installer
type: kubernetes.io/dockerconfigjson
